# Generated by Django 5.0.1 on 2024-02-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_appointmenttimeslot_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='date',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
