# Generated by Django 5.0.1 on 2024-02-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_doctor_alter_appointment_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], default='male', max_length=10),
        ),
    ]
