# Generated by Django 5.0.1 on 2024-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_doctor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='AppointmentTimeSlot',
        ),
    ]
