# Generated by Django 5.0.1 on 2024-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_appointment_time_delete_appointmenttimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã huỷ'), ('examination_in_progress', 'Đang khám'), ('exam_completed', 'Đã khám')], default='Chờ xác nhận', max_length=40),
        ),
    ]
