# Generated by Django 5.0.1 on 2024-02-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('Nội khoa', 'Nội khoa'), ('Ngoại khoa', 'Ngoại khoa'), ('Nhi khoa', 'Nhi khoa'), ('Sản khoa', 'Sản khoa'), ('Răng hàm mặt', 'Răng hàm mặt'), ('Da liễu', 'Da liễu'), ('Tim mạch', 'Tim mạch'), ('Thần kinh', 'Thần kinh'), ('Tai mũi họng', 'Tai mũi họng'), ('Mắt', 'Mắt'), ('Nội tiết', 'Nội tiết'), ('Chấn thương chỉnh hình', 'Chấn thương chỉnh hình'), ('Chẩn đoán hình ảnh', 'Chẩn đoán hình ảnh'), ('Y học cổ truyền', 'Y học cổ truyền')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
