# Generated by Django 5.0.1 on 2024-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_remove_invoice_is_paid_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
