# Generated by Django 5.0.1 on 2024-02-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_invoice_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Tiền mặt', 'Tiền mặt'), ('e-Wallet', 'e-Wallet')], max_length=20, null=True),
        ),
    ]
