# Generated by Django 5.0.1 on 2024-02-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='is_available',
        ),
    ]
